title: Mahmoud Karam
logo: /assets/img/logo.png
description: Currently I am utilizing 17+ years of experience as a professional IT Data management expert in Enterprise/Telecom environment to develop and impelement a digital transformation roadmap for profitability management department that responsible of the whole STC costing and profitability and generating P&L statement.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
